pipeline {
  agent any

  stages {
    stage ('Compile stage') {
      steps {
        sh 'echo coucou'
        withMaven(maven: 'maven3') {
          sh 'mvn clean compile'
        }
      }
    }
  }
}